baseURL = 'https://oldmill1.github.io/blog/'
languageCode = 'en-us'
title = 'Blog'
theme = "archie"

[params]
mode = "dark"
title = "Blog"
subtitle = "Written by a fully grown-ass man, not AI... yes, believe it."

[markup.highlight]
style = "dracula"
